docs: update readme
Open-Attestation/token-registry pull request #179
Opened 2023-12-29 08:55 UTC by rollerchloe

Mainly editing the content, so that this readme can be retrieved by documentation website as a remote file

2024-02-19 08:28 UTC, yapyuyou requested changes

2024-02-19 08:28 UTC, yapyuyou commented on README.md
> +Starting from V4, OpenAttestation includes an easy and cost-effective way to deploy the contracts and meanwhile keep the options available for advanced users to set up the contracts in a preferable w
The V4 here is referring to the token registry (this repo) specifically, not OpenAttestation. We can change this to "Starting from v4, the token registry..."

2024-02-19 08:28 UTC, yapyuyou commented on README.md
> +To grant roles to the users or revoke roles from them, the admin user can call on the token contract the following functions:
```suggestion
To grant roles to the users or revoke roles from them, the admin user can call the following functions:
```

2024-02-19 08:28 UTC, yapyuyou commented on README.md
> +<!--Flag: Question here: Have the contracts gone thru formal audits so far? If not, shall we move this paragraph to the beginning to inform the user before they get started?-->
To my knowledge no, but I think we can leave it here at the bottom as we don't want to scare potential users away

2024-02-19 08:30 UTC, rollerchloe commented on README.md
> +To grant roles to the users or revoke roles from them, the admin user can call on the token contract the following functions:
removed

2024-02-20 02:25 UTC, yapyuyou approved these changes

2024-02-20 07:18 UTC, merged